- hosts: server
  connection: local
  gather_facts: false
  tasks:
  - name: Copy public ssh key to remote hosts
    shell: ssh-copy-id -i ./keys/id_rsa.pub {{ ansible_user }}@{{ ansible_host }} -p {{ ansible_port }}
