- hosts: server
  gather_facts: false
  vars:
    service_name: vpn-pptp
  tasks:
  - name: Copy Docker files
    copy:
      dest: "/tmp/dockerfiles"
      src: "../../dockerfiles/{{ service_name }}"
      
  - name: Build Docker image from Dockerfile
    docker_image:
      name: "{{ service_name }}"
      path: "/tmp/dockerfiles/{{ service_name }}"
      pull: false
      force: yes
      state: present
