- hosts: router
  gather_facts: false
  roles:
    - openwrt_uci
  tasks:
  - name: Setup OpenWRT router wireless to use WEP Shared Key enterprise as security encryption
    uci: command=set key="wireless.@wifi-iface[0].ssid" value="{{ router_wireless_ssid }}"
  - uci: command=set key="wireless.@wifi-iface[0].encryption" value="wep-shared"
  - uci: command=set key="wireless.@wifi-iface[0].key" value="1"
  - uci: command=set key="wireless.@wifi-iface[0].key1" value="s:{{ router_wireless_wep_password }}"
  - raw: uci commit

- include: router_reload_network.yml
